nohup: ignoring input
[I 2024-09-22 16:36:10.785 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-09-22 16:36:10.799 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-09-22 16:36:10.829 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-09-22 16:36:10.858 ServerApp] notebook | extension was successfully linked.
[I 2024-09-22 16:36:10.874 ServerApp] Writing Jupyter server cookie secret to /home/ec2-user/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2024-09-22 16:36:11.981 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-09-22 16:36:12.088 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-09-22 16:36:12.115 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-09-22 16:36:12.117 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-09-22 16:36:12.119 LabApp] JupyterLab extension loaded from /home/ec2-user/environment/jupyterlab-venv/lib64/python3.9/site-packages/jupyterlab
[I 2024-09-22 16:36:12.119 LabApp] JupyterLab application directory is /home/ec2-user/environment/jupyterlab-venv/share/jupyter/lab
[I 2024-09-22 16:36:12.120 LabApp] Extension Manager is 'pypi'.
[I 2024-09-22 16:36:12.149 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-09-22 16:36:12.177 ServerApp] notebook | extension was successfully loaded.
[I 2024-09-22 16:36:12.178 ServerApp] Serving notebooks from local directory: /home/ec2-user/environment
[I 2024-09-22 16:36:12.178 ServerApp] Jupyter Server 2.14.2 is running at:
[I 2024-09-22 16:36:12.178 ServerApp] http://ip-10-0-1-124.ec2.internal:8888/lab?token=6bda2c2bb91ed63e905a3fd45528cd8aa032797b595989c1
[I 2024-09-22 16:36:12.178 ServerApp]     http://127.0.0.1:8888/lab?token=6bda2c2bb91ed63e905a3fd45528cd8aa032797b595989c1
[I 2024-09-22 16:36:12.178 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2024-09-22 16:36:12.207 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2024-09-22 16:36:12.207 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/ec2-user/.local/share/jupyter/runtime/jpserver-2739-open.html
    Or copy and paste one of these URLs:
        http://ip-10-0-1-124.ec2.internal:8888/lab?token=6bda2c2bb91ed63e905a3fd45528cd8aa032797b595989c1
        http://127.0.0.1:8888/lab?token=6bda2c2bb91ed63e905a3fd45528cd8aa032797b595989c1
[I 2024-09-22 16:36:12.971 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2024-09-22 16:37:41.095 LabApp] Build is up to date
[I 2024-09-22 16:37:43.577 ServerApp] Writing notebook-signing key to /home/ec2-user/.local/share/jupyter/notebook_secret
[W 2024-09-22 16:37:43.580 ServerApp] Notebook C2_W3_Assignment.ipynb is not trusted
[I 2024-09-22 16:37:45.799 ServerApp] Kernel started: fda554d8-a193-47f7-969e-15337b8ab5d2
[I 2024-09-22 16:37:46.811 ServerApp] Connecting to kernel fda554d8-a193-47f7-969e-15337b8ab5d2.
[I 2024-09-22 16:37:47.279 ServerApp] Connecting to kernel fda554d8-a193-47f7-969e-15337b8ab5d2.
[I 2024-09-22 16:37:47.748 ServerApp] Connecting to kernel fda554d8-a193-47f7-969e-15337b8ab5d2.
[I 2024-09-22 16:39:46.774 ServerApp] Saving file at /C2_W3_Assignment.ipynb
[I 2024-09-22 16:45:47.527 ServerApp] Saving file at /C2_W3_Assignment.ipynb
[I 2024-09-22 16:47:48.074 ServerApp] Saving file at /C2_W3_Assignment.ipynb
[I 2024-09-22 16:49:50.302 ServerApp] Saving file at /C2_W3_Assignment.ipynb
[I 2024-09-22 16:51:50.826 ServerApp] Saving file at /C2_W3_Assignment.ipynb
[I 2024-09-22 16:53:51.371 ServerApp] Saving file at /C2_W3_Assignment.ipynb
[I 2024-09-22 16:55:52.423 ServerApp] Saving file at /C2_W3_Assignment.ipynb
[I 2024-09-22 16:57:52.931 ServerApp] Saving file at /C2_W3_Assignment.ipynb
[I 2024-09-22 16:59:55.590 ServerApp] Saving file at /C2_W3_Assignment.ipynb
[I 2024-09-22 17:01:56.777 ServerApp] Saving file at /C2_W3_Assignment.ipynb
[I 2024-09-22 17:03:57.981 ServerApp] Saving file at /C2_W3_Assignment.ipynb
[I 2024-09-22 17:05:58.709 ServerApp] Saving file at /C2_W3_Assignment.ipynb
[I 2024-09-22 17:09:59.247 ServerApp] Saving file at /C2_W3_Assignment.ipynb
[I 2024-09-22 17:11:59.758 ServerApp] Saving file at /C2_W3_Assignment.ipynb
[I 2024-09-22 17:14:02.693 ServerApp] Saving file at /C2_W3_Assignment.ipynb
[E 2024-09-22 17:15:06.624 ServerApp] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/home/ec2-user/environment/jupyterlab-venv/lib64/python3.9/site-packages/tornado/web.py", line 1753, in _execute
        raise HTTPError(405)
    tornado.web.HTTPError: HTTP 405: Method Not Allowed
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ec2-user/environment/jupyterlab-venv/lib64/python3.9/site-packages/tornado/web.py", line 1298, in send_error
        self.write_error(status_code, **kwargs)
      File "/home/ec2-user/environment/jupyterlab-venv/lib64/python3.9/site-packages/jupyter_server/base/handlers.py", line 739, in write_error
        html = self.render_template("%s.html" % status_code, **ns)
      File "/home/ec2-user/environment/jupyterlab-venv/lib64/python3.9/site-packages/jupyter_server/base/handlers.py", line 665, in render_template
        ns.update(self.template_namespace)
      File "/home/ec2-user/environment/jupyterlab-venv/lib64/python3.9/site-packages/jupyter_server/base/handlers.py", line 675, in template_namespace
        logged_in=self.logged_in,
      File "/home/ec2-user/environment/jupyterlab-venv/lib64/python3.9/site-packages/jupyter_server/base/handlers.py", line 198, in logged_in
        user = self.current_user
      File "/home/ec2-user/environment/jupyterlab-venv/lib64/python3.9/site-packages/tornado/web.py", line 1424, in current_user
        self._current_user = self.get_current_user()
      File "/home/ec2-user/environment/jupyterlab-venv/lib64/python3.9/site-packages/jupyter_server/base/handlers.py", line 177, in get_current_user
        raise RuntimeError(msg)
    RuntimeError: Calling `Template404.get_current_user()` directly is deprecated in jupyter-server 2.0. Use `self.current_user` instead (works in all versions).
[W 2024-09-22 17:15:06.630 ServerApp] 405 CONNECT example.com:443 (@154.213.184.18) 5.52ms referer=None
[I 2024-09-22 17:16:03.434 ServerApp] Saving file at /C2_W3_Assignment.ipynb
[I 2024-09-22 17:18:05.669 ServerApp] Saving file at /C2_W3_Assignment.ipynb
[I 2024-09-22 17:20:07.439 ServerApp] Saving file at /C2_W3_Assignment.ipynb
